[package]
name = "create"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
dialoguer = "0.11.0"
serde = { version = "1.0.204", features = ["derive"] } 
serde_json = "1.0.122"
chrono = "0.4"
ulid = "1.1.3"
